version: '3'

services:
  frontend:
    build: 
      context: .
      args:
        - NPM_TIMEOUT=600000
    ports:
      - "3001:3000"
    volumes:
      - ./src:/app/src
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: 
      context: ./backend
      args:
        - NPM_TIMEOUT=600000
    ports:
      - "5000:5000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/logs:/app/logs
    environment:
      - PORT=5000
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/zk-auth-voting
      - JWT_SECRET=dev-secret-key-change-in-production
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data: 